proj_NAME: EAM_test

dataset: CustomDataset_G
traindataset_args:
  mask_density: 50
  image_dir:
    - filedata/cotton0610
    - filedata/cotton0618
    - filedata/waterbase

valdataset_args:
#  mask_density: 20
  image_dir:
    - filedata/cotton0610
    - filedata/cotton0618
#    - filedata\waterbase

testdataset_args:
#  mask_density: 20
  image_dir:
    - filedata/cotton0610
    - filedata/cotton0618

iters: 150000
batch_size: 6
lr: 0.0004

resume: null

generatorG:
  type: Generator_Unet
#  type: Generator_UnetNoEAM
#  type: null


loss_weights:
  BCELoss: 10
  L1Loss: 0
  DiceLoss: 10
  PerceptualLoss: 10
#  StyleLoss: 10000


discriminatorG:
  type: PatchGAN
#  type: null